---

- hosts: all
  become: true
  tasks:

  - name: update repository index 
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-modphp
      state: latest
   
