---

- hosts: all
  become: true
  tasks:

  - name: update repository index 
    apt:
      update_cache: yes

  - name: remove apache2 package
    apt:
      name: apache
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-modphp
      state: absent
   
